#Currently, there is a bug where meson is not able to find and inject the
#correct link/includes if you're using modern Intel. This provides a hotfix
#until this is patched in issue #15260 
[binaries]
fortran = 'mpiifx'
cpp = 'icx'
c = 'icx'
[properties]
fortran_args = ['-w', '-fPIE', '-fPIC']

