#!/bin/bash
#SBATCH -J adcprep           # Job name
#SBATCH -o adcprep.o%j       # Name of stdout output file
#SBATCH -e adcprep.e%j       # Name of stderr error file
#SBATCH -p skx-normal          # Queue (partition) name
#SBATCH -N 1               # Total # of nodes 
#SBATCH -n 1              # Total # of mpi tasks
#SBATCH -t 01:00:00        # Run time (hh:mm:ss)
#SBATCH --mail-type=all    # Send email at begin and end of job
#SBATCH --mail-user=markloveland@utexas.edu
#SBATCH -A TG-DMS080016N        # Project/Allocation name (req'd if you have more than 1)

module list
./adcprep <in.prep1
./adcprep <in.prep2

