#!/bin/bash
#SBATCH -J Neches_Small_run
#SBATCH -A TG-DMS080016N
#SBATCH -o padcirc.o%j
#SBATCH -e padcirc.o%j
#SBATCH -p skx-normal
#SBATCH -N 2
#SBATCH -n 96
#SBATCH -t 03:00:00

#SBATCH --mail-user=markloveland@utexas.edu
#SBATCH --mail-type=begin        # email me when the job starts
#SBATCH --mail-type=end          # email me when the job finishes
date>run.timing
ibrun ./padcirc -W 2
date>>run.timing
