  PPFC          := gfortran
  FC            := gfortran
  PFC           := not-specified
  FFLAGS1       :=  -O2 -DLINUX
  FFLAGS2       :=  -O2 -DLINUX
  FFLAGS3       :=  -O2 -DLINUX
  FFLAGS4       :=  -O2 -DLINUX
  DA            :=  -DREAL8 -DCSCA -DLINUX
  DP            :=  -DREAL8 -DCSCA -DLINUX -DCMPI -DBLKOUT
#  DP            :=  -DREAL8 -DCSCA -DIBM -W132 -DCMPI -DBLKOUT
  DPRE          :=  -DREAL4 -DLINUX
  DPRE2         :=  -DREAL4 -DLINUX
  IMODS         :=  -I 
  CC            :=  mpicc
  CFLAGS        :=  -I. -O2 -DIBM
  LDFLAGS       :=
  LIBS          :=  -L ../metis  -lmetis -lU77
  PERFLIBS      :=
# PERFLIBS      :=  -L$(HOME)/bin -lparaperf  -lezstub 
  MSGLIBS       :=  -lm
