#!/bin/bash                                                                                                       

#SBATCH -J dgswem      # Job name                                                                          
#SBATCH -A Oil # seDawson
#SBATCH -o dgswem.o%j       # Name of stdout output file (%j expands to jobId)   
#SBATCH -e dgswem.e%j       # Name of stdout output file (%j expands to jobId)                               
#SBATCH -p development   # Queue name                                                         
#SBATCH -n 256             #Total number of mpi tasks requested
#SBATCH -t 4:00:00      # Run time (hh:mm:ss) - 1.5 hours                                                   
#SBATCH --mail-user=michoski@ices.utexas.edu
#SBATCH --mail-type=ALL 

ibrun ./padcirc

