name: CI
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v5
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: env-gcc
          environment-file: environment_gcc.yml
          auto-activate: false
      - run: |
          conda info
          export PKG_CONFIG_PATH=$CONDA_PREFIX/lib/pkgconfig
          meson setup build -Dparallel=true -Dnetcdf=true
          cd build
          meson compile

      - run: |
          cd tests
          pytest -s test_run.py --binpath ../build
