name: CI
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v3
      - uses: actions/checkout@v5
      - run: |
          conda env create --file environment_gcc.yml
      - run: |
          conda init
          conda activate env-gcc
          meson setup build -Dparallel=true -Dnetcdf=true
          cd build
          meson compile
